[project]
name = "gracchusconsulting-static-site"
version = "0.1.0"
description = "Gracchus Consulting static site"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pelican[markdown]>=4.11.0",
]
